### ISSUE TITLE
With RDP I cannot do multiple select with the mouse

### ISSUE THREAD

**Issue by curpin** [OliverKohlDSc/Terminals#17]
When I do RDP and I am on the desktop screen of the remote machine, I am unable to do a multiple select with the mouse.
When you do a mouse click on the desktop and drag your hand, you usually see a re sizeable square, here however, nothing happens.

**Comment by OliverKohlDSc** [comment]
Thanks Toni for reporting.
This will be solved in the next release.

**Comment by OliverKohlDSc** [comment]
@curpin 
The issue has been fixed.
Please try the latest release https://github.com/OliverKohlDSc/Terminals/releases/tag/4.9.1.0

**Comment by curpin** [comment]
I have just installed the 4.9.1.0 and the issue is still there.
I am not able to do multi-select by dragging the mouse on the Desktop or in Explorer...

**Comment by OliverKohlDSc** [comment]
@curpin Thanks I'll have a look at it again.

**Comment by OliverKohlDSc** [comment]
Hi @curpin
After the feedback of five guys the error should be solved now.
Can you confirm this?

Same tag version but new release https://github.com/OliverKohlDSc/Terminals/releases/tag/4.9.1.0

Thanks Oliver

**Comment by curpin** [comment]
This looks like fixed now, thank you
